path_data: /home/mqueyrel/Documents/work/tmp/simulation_files/camisim/dataset/illumina_abundance_balanced_species_V2_2_metagenome2vec_embeddings/mil.csv
path_model: /home/mqueyrel/Documents/work/tmp/vae
path_metadata: /home/mqueyrel/Documents/work/tmp/simulation_files/camisim/dataset/illumina_abundance_balanced_species_V2_2_metagenome2vec/metadata.csv
dataset_name: vae

batch_size: 2
n_steps: 50
learning_rate: 0.001
weight_decay: 0.1
dropout: 0.2
vae_struct: 40,1,1
n_cpus: 12
n_iterations: 10
id_gpu: -1
n_memory: 4
ressources: cpu:3,gpu:0.,worker:2
cross_validation: 2
test_size: 0.3
computation_type: vae
tune: "True"
disease: ill
